### ISSUE TITLE
[1주차] todo-list ERD 설계 및 DB 연동 -#1

### ISSUE THREAD

**Issue by kws9208** [Like-Lion-NSU/spring-server-study#7]
📋 이슈 내용
todo-list ERD 설계 및 DB 연동

✅ 체크리스트
- [x]  Todo entity 구현
- [x] User entity 구현
 - [x] Todo Repository 구현
 - [x] User Repository 구현
 - [x] JPA 없이 repository 구현

📚 레퍼런스
https://velog.io/@jeukoh26/%EC%8A%A4%ED%94%84%EB%A7%81-%EC%9E%85%EB%AC%B8-%EA%B9%80%EC%98%81%ED%95%9C-%EA%B0%95%EC%9D%98-%EC%9A%94%EC%95%BD-2-
